### ISSUE TITLE
ExecuteCellSet bug

### ISSUE THREAD

**Issue by izverev-icm** [bdebaere/Unofficial.Microsoft.AnalysisServices.AdomdClientNetCore#4]
Hi! Thanks for the library! I found that ExecuteCellSet() throws an exception due to wrong code in MDDatasetFormatter.ReadCellInfo() method. There is commented out line "goto IL_136;", it should be restored (and label moved out from the try block), then it works.

**Comment by bdebaere** [comment]
Thank you! I will release a new version with this code change.

**Comment by bdebaere** [comment]
@izverev-icm The new version was released a couple of days ago. Can you try it out and see if it solves your issue? Thanks in advance.

**Comment by bdebaere** [comment]
Closing because no response was given. Feel free to open another issue if it is not resolved yet.
